apiVersion: v1
kind: Service
metadata:
  name: seif-svc
spec:
  type: {{ .Values.seif.service.type }}
  ports:
    - port: {{ .Values.seif.service.port }}
      targetPort: {{ .Values.seif.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.seif.name }}
