apiVersion: v1
kind: Service
metadata:
  name: agent-svc
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: {{ .Values.agent.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.agent.service.nodePort }}
  selector:
    app: {{ .Values.agent.name }}
